query GetMenuItems{
    getMenuItems{
        title
        icon
        layer
        activate
        subItems{
            title
            icon
            layer
            activate
            subItems{
                title
                icon
                layer
                activate
                description
                documentLink
                i18nKey
            }
            description
            documentLink
            i18nKey
        }
        description
        documentLink
        i18nKey
    }
}