query QueryEvents($condition: EventQueryCondition){
    queryEvents(condition: $condition){
        events{
            uuid
            source{
                service
                serviceInstance
                endpoint
            }
            name
            type
            message
            parameters{
                key
                value
            }
            startTime
            endTime
            layer
        }
    }
}