query QueryContinuousProfilingMonitoringInstances($serviceId: ID!, $target: ContinuousProfilingTargetType!){
    queryContinuousProfilingMonitoringInstances(serviceId: $serviceId, target: $target){
        id
        name
        attributes{
            name
            value
        }
        triggeredCount
        lastTriggerTimestamp
        processes{
            id
            name
            detectType
            labels
            triggeredCount
            lastTriggerTimestamp
        }
    }
}