query QueryContinuousProfilingServiceTargets($serviceId: ID!){
    queryContinuousProfilingServiceTargets(serviceId: $serviceId){
        type
        checkItems{
            type
            threshold
            period
            count
            uriList
            uriRegex
        }
        triggeredCount
        lastTriggerTimestamp
    }
}