query ReadNullableMetricsValue($condition: MetricsCondition!, $duration: Duration!){
    readNullableMetricsValue(condition: $condition, duration: $duration){
        value
        isEmptyValue
    }
}