query ReadSampledRecords($condition: TopNCondition!, $duration: Duration!){
    readSampledRecords(condition: $condition, duration: $duration){
        name
        id
        value
        refId
    }
}